<a href="https://colab.research.google.com/github/Apichaya-bu/229352-stat-learning-for-data2/blob/main/%E0%B8%AA%E0%B8%B3%E0%B9%80%E0%B8%99%E0%B8%B2%E0%B8%82%E0%B8%AD%E0%B8%87_Lab08_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Statistical Learning for Data Science 2 (229352)
#### Instructor: Donlapark Ponnoprat

#### [Course website](https://donlapark.pages.dev/229352/)

## Lab #8

There are several deep learning frameworks in Python.

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/PyTorch_logo_black.svg/2560px-PyTorch_logo_black.svg.png" width="100"/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://upload.wikimedia.org/wikipedia/commons/2/2d/Tensorflow_logo.svg" width="40"/><img src="https://assets-global.website-files.com/621e749a546b7592125f38ed/62277da165ed192adba475fc_JAX.jpg" width="100"/>

In this Lab, we will use PyTorch

In [2]:
import numpy as np

import torch

# Tensor basics

## Basic tensor creation

### Creating a scalar (1D) tensor

In [3]:
scalar = torch.tensor(7)
print(scalar)


tensor(7)


### Convert a tensor to scalar

In [4]:
scalar_value = scalar.item()
print(scalar_value)


7


### Creating 2D tensor

In [5]:
tensor_2d = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(tensor_2d)


tensor([[1, 2, 3],
        [4, 5, 6]])


## Tensor and Numpy

### Convert from tensor to numpy array

In [6]:
t = torch.ones(5)
n = t.numpy()
print(n)


[1. 1. 1. 1. 1.]


### Convert from numpy array to tensor

In [7]:
n = np.ones(5)
t = torch.from_numpy(n)
print(t)


tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


## PyTorch and GPU

check if GPU is available

In [17]:
torch.cuda.is_available()

True

## Basic operations

In [18]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
print(a + b)
print(a * b)


tensor([5, 7, 9])
tensor([ 4, 10, 18])


### Matrix multiplication

In [19]:
mat1 = torch.randn(2, 3)
mat2 = torch.randn(3, 2)
res = torch.matmul(mat1, mat2)
print(res)


tensor([[ 0.6451,  1.6142],
        [-2.3318, -4.4952]])


### Matrix transpose

In [20]:
x = torch.randn(2, 3)
print(x.T)


tensor([[ 0.1694,  0.9099],
        [ 0.8610, -1.7182],
        [ 0.8523,  1.1203]])


## Creating a specific type of tensor

In [12]:
double_tensor = torch.ones(2, 2, dtype=torch.float64)
print(double_tensor)


tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)


## Tensor's shape

### Checking the shape of a tensor

In [13]:
x = torch.zeros(5, 3)
print(x.shape)


torch.Size([5, 3])


### Changing the shape of a tensor

In [14]:
x = torch.randn(4, 4)
y = x.reshape(16)
z = x.view(-1, 8)
print(y.shape, z.shape)


torch.Size([16]) torch.Size([2, 8])


In general, use `reshape`, but if you are worried about the memory usage, use `view`.

### Stacking and concatenating tensors

In [15]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

# Concatenate (ต่อกันในแกนเดิม)
cat_res = torch.cat((x, y), dim=0)

# Stack (วางซ้อนกันเกิดแกนใหม่)
stack_res = torch.stack((x, y))
print(cat_res)
print(stack_res)


tensor([1, 2, 3, 4, 5, 6])
tensor([[1, 2, 3],
        [4, 5, 6]])


### Squeezing a tensor (removing an extra dimension)

In [21]:
# Squeeze: เอา dimension ที่เป็น 1 ออก
x = torch.zeros(1, 10)
print(x.squeeze().shape)


torch.Size([10])


### Unsqueezing a tensor (adding an extra dimension)

In [22]:
# Unsqueeze: เพิ่มมิติในตำแหน่งที่กำหนด
y = torch.zeros(10)
print(y.unsqueeze(dim=0).shape)


torch.Size([1, 10])


## Indexing

In [23]:
P = torch.arange(12).reshape(3,4)
print(P)
print(P[0])
print(P[:, 0])
print(P[-1])
print(P[:, -1])
print(P[-2:])
print(P[:, -2:])

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([0, 1, 2, 3])
tensor([0, 4, 8])
tensor([ 8,  9, 10, 11])
tensor([ 3,  7, 11])
tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 2,  3],
        [ 6,  7],
        [10, 11]])


# Exercise

In this exercise, we will simulate data to perform linear regression with 200 rows and 7 variables.

1. Create three random $N(0,1)$ tensors: `X`, `b` and `e` with `X.shape = (200, 7)`, `b.shape = (8, 1)` and `e.shape = (200, 1)` respectively.
2. Create a tensor that contains only 1's with shape `(200, 1)`.
3. Modify tensor `X` by adding the tensor in 2. as the first column.
4. Compute `y` using the following formula:
$$ y = Xb + e $$.
5. Fit a linear regression to the data `X` and `y` and obtain a tensor of estimated coefficient `b_hat`. The formula for `b_hat` is given by:
$$ \hat{b} = (X^TX)^{-1}X^Ty $$
Note: use `torch.inverse(...)` to calculate the inverse
6. Compute the predictions `y_hat`, given by:
$$ \hat{y} = X\hat{b} $$
7. Convert both `y` and `y_hat` from tensor to Numpy array and calculate MSE:
$$ MSE = \frac{1}{200}\sum_{i=1}^{200} (y_i - \hat{y}_i)^2 $$

In [24]:
X = torch.tensor([[2, 3, 2], [4, 6, 7], [7, 2, 4]])
print(X)

X = torch.tensor([[1, 2, 3, 2], [1, 4, 6, 7], [1, 7, 2, 4]])
print(X)

tensor([[2, 3, 2],
        [4, 6, 7],
        [7, 2, 4]])
tensor([[1, 2, 3, 2],
        [1, 4, 6, 7],
        [1, 7, 2, 4]])


In [26]:
# 1. สร้าง random tensors N(0,1) ตามขนาดที่กำหนด
X = torch.randn(200, 7)
b = torch.randn(8, 1)
e = torch.randn(200, 1)

# 2. สร้าง tensor ที่มีเลข 1 ทั้งหมดขนาด (200, 1)
ones = torch.ones(200, 1)

# 3. เพิ่ม ones เข้าไปเป็นคอลัมน์แรกของ X (กลายเป็นขนาด 200, 8)
X = torch.cat((ones, X), dim=1)

# 4. คำนวณ y = Xb + e
y = torch.matmul(X, b) + e

# 5. คำนวณ b_hat (Estimated Coefficient)
XTX_inv = torch.inverse(torch.matmul(X.T, X))
b_hat = torch.matmul(torch.matmul(XTX_inv, X.T), y)

# 6. คำนวณการทำนาย y_hat = X * b_hat
y_hat = torch.matmul(X, b_hat)

# 7. แปลงเป็น Numpy และคำนวณค่า MSE
y_np = y.numpy()
y_hat_np = y_hat.numpy()
mse = np.mean((y_np - y_hat_np)**2)

print(f"MSE Value: {mse}")
print(f"b_hat shape: {b_hat.shape}")


MSE Value: 1.171360969543457
b_hat shape: torch.Size([8, 1])
